name: "FusionTP"
author: "Lord_Fusion"
version: "1.100"

main: "io.github.lordfusion.fusiontp.FusionTP"
softdepend: [Multiverse-Core]

commands:
  fusiontp:
    description: "Teleport one player to another player."
    usage: /<command> [player] [player]
    permission: FusionTP.direct.to
    permission-message: "[Fusion] You don't have <permission>"
    aliases: [ftp]
  fusiontphere:
    description: "Teleport a player to you."
    usage: /<command> [player]
    permission: FusionTP.direct.here
    permission-message: "[Fusion] You don't have <permission>"
    aliases: [ftphere, ftph]
  fusionspawntp:
    description: "Teleport a player to Spawn."
    usage: /<command> [player]
    permission: FusionTP.direct.spawn
    permission-message: "[Fusion] You don't have <permission>"
    aliases: [fstp, fspawntp, spawntp, stp]

  fusiontest:
    description: "DEVELOPERS ONLY: Test a method from the code."
    permission: FusionTP.developer.test
    permission-message: "[Fusion] You don't have <permission>"