name: "FusionTP"
author: "Lord_Fusion"
version: "1.0"

main: "io.github.lordfusion.fusiontp.FusionTP"
softdepend: [Multiverse]

commands:
  fusiontp:
    description: "Teleport one player to another player. (ONLINE ONLY)"
    usage: /<command> [player] [player]
    permission: FusionTP.direct.to
    permission-message: "[Fusion] You don't have <permission>"
    aliases: [ftp]
  fusiontphere:
    description: "Teleport a player to you. (ONLINE ONLY)"
    usage: /<command> [player]
    permission: FusionTP.direct.here
    permission-message: "[Fusion] You don't have <permission>"
    aliases: [ftphere, ftph]

  fusiontpa:
    description: "Request to teleport to another player."
    usage: /<command> [player]
    permission: FusionTP.request.to
    permission-message: "[Fusion] You don't have <permission>"
    aliases: [ftpa]
  fusiontpahere:
    description: "Request another player to teleport to you."
    usage: /<command> [player]
    permission: FusionTP.request.here
    permission-message: "[Fusion] You don't have <permission>"
    aliases: [ftpah, ftpahere]

  fusiontpaccept:
    description: "Accept a pending teleport request."
    usage: /<command>
    permission: FusionTP.request.accept
    permission-message: "[Fusion] You don't have <permission>"
    aliases: [ftpaccept]
  fusiontpdeny:
    description: "Deny a pending teleport request."
    usage: /<command>
    permission: FusionTP.request.deny
    permission-message: "[Fusion] You don't have <permission>"
    aliases: [ftpdeny]